spring:
  datasource:
    url: jdbc:mariadb://211.53.209.159:3306/java_class
    username: student
    password: a1235
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: mapper/**/*.xml

